apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-02-28T13:55:57Z"
  labels:
    kubernetes.io/metadata.name: job-processig
  name: job-processig
  resourceVersion: "43156"
  uid: 4e2d011a-6157-4b92-8463-a081473af813
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
