apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: job-processig
type: Opaque
stringData:
  connection: "postgresql://jobuser:jobpass123@postgres.job-processig.svc.cluster.local:5432/jobqueue?sslmode=disable"